[build]
  publish = "build/"
  command = "npm run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "12" }

[context.branch-deploy.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/api/*"
  to = "https://legion-td-wiki.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-sitemap"
