version: "3"
services:
  mongo:
    image: mongo:4
    restart: always
    container_name: legionTD_mongo
    ports:
      - 27017:27017

  mongoUI:
    image: mongo-express:latest
    restart: always
    container_name: legionTD_mongoUI
    ports:
      - 8081:8081
