export const tuskarrUnit = {
  Name: "tuskarr",
  Builder: "artic",
  "Unit Tier": 1,
  "Gold Cost": 20,
  "Food Cost": 1,
  Upgradeable: true,
  "Max Upgrade Gold Cost": 70,
  "Total Food Cost with Upgrade": 1,
  "Base Unit Name": null,
  "Upgraded Name": ["tuskarr spearman"],
  "Base Min Hit": 16,
  "Base Max Hit": 17,
  "Attack Speed": 1.4,
  "Attack Speed Class": "fast",
  Range: 100,
  "Melee / Ranged": "melee",
  "Hit Points": 95,
  Mana: 0,
  "Attack Type": "normal",
  "Defense Type": "medium",
  "Attack Effectiveness Order": [
    "medium",
    "unarmored",
    "light",
    "heavy",
    "fortified",
  ],
  "Attack Strength": "medium",
  "Attack Weakness": ["fortified"],
  "Defense Effectiveness Order": [
    "magic",
    "pierce",
    "siege",
    "chaos",
    "normal",
  ],
  "Defense Strength": ["magic"],
  "Defense Weakness": ["normal"],
  Abilities: null,
  "Ability Type": null,
  "Ability Description": null,
  "Has Aura": false,
  "Can Buff": false,
  "Can Debuff": false,
  "Can Splash": false,
  "Can Heal": false,
  "Can Stun": false,
  "Can Summon": false,
  ID: "H1wkO11",
};

export const tuskarrSpearmanUnit = {
  Name: "tuskarr spearman",
  Builder: "artic",
  "Unit Tier": 1,
  "Gold Cost": 70,
  "Food Cost": 0,
  Upgradeable: false,
  "Max Upgrade Gold Cost": 0,
  "Total Food Cost with Upgrade": 0,
  "Base Unit Name": "tuskarr",
  "Upgraded Name": null,
  "Base Min Hit": 16,
  "Base Max Hit": 17,
  "Attack Speed": 0.6,
  "Attack Speed Class": "very fast",
  Range: 450,
  "Melee / Ranged": "ranged",
  "Hit Points": 280,
  Mana: 0,
  "Attack Type": "pierce",
  "Defense Type": "medium",
  "Attack Effectiveness Order": [
    "light",
    "unarmored",
    "medium",
    "heavy",
    "fortified",
  ],
  "Attack Strength": "light",
  "Attack Weakness": ["fortified"],
  "Defense Effectiveness Order": [
    "magic",
    "pierce",
    "siege",
    "chaos",
    "normal",
  ],
  "Defense Strength": ["magic"],
  "Defense Weakness": ["normal"],
  Abilities: ["ice spear"],
  "Ability Type": ["slow - movement"],
  "Ability Description": [
    "Adds 12 cold damage to each attack slowing a target enemy unit's movement by 60%",
  ],
  "Has Aura": false,
  "Can Buff": false,
  "Can Debuff": true,
  "Can Splash": false,
  "Can Heal": false,
  "Can Stun": false,
  "Can Summon": false,
  ID: "wD7V92U",
};
