version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/backend"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/data-import"
    update_schedule: "monthly"
